platform :ios, '13.0'

source 'https://github.com/oititec/ios-artifactory.git'
source 'https://cdn.cocoapods.org'

target 'Example' do
  use_frameworks!

  # Pods
  pod 'CertifaceSDK', path: '../'
end